---
title: "Homework-02"
format: html
author: L. Harvey 
editor: visual
embed-resources: TRUE 
---

## Homework #2 

### Exercise 2.1: Demystifying "identified." 

Which of the following is the best definition of the term *identified* as in “this variation has identified the effect we’re interested in”?\
a. We've generated the data by conducting a controlled experiment in which treatment is randomly \
assigned. \
b. In the data generating process, the only reason why we see variation in the outcome variable is \
because of the treatment variable. \
c. The relationship we are looking at in the data actually tests a hypothesis. \
d. In the variation we use, there's no reason we'd see any relationship at all except for the effect we're \
interested in.

The answer to this question is: D) "In the variation we use, there's no reason we'd see any relationship at all except for the effect we're interested in."

### Exercise 2.2: Caviar, Anyone? 

You read about a new study with the headline “eating caviar linked to longer lifespan.” The study’s research question is “does eating caviar make you live longer?” In the study’s data, they find that people who eat caviar have, on average, longer lifespans than people who don’t.

a.  What are some alternate explanations for this relationship?

    One alternate explanation for this relationship is the role that socioeconomic status plays in life chances. Specifically, caviar is a low-calorie, high-monetary-cost food item that (because it is low-calorie and high-cost) is not a reasonable purchase for people belonging to lower social strata. Thus, it is reasonable to assume that people who *do* consume this ~~pretentious~~ food belong to a higher social class and have more disposable income. Consequently, with having more money, one has access to better healthcare, leading there to be a seemingly-causal (but actually flimsy) link between caviar consumption and longer lifespan. \
    \
    An alternate (and less convincing) explanation for this relationship could argue that seafood-based diets correlate with [longer lifespans](https://www.sciencedirect.com/science/article/pii/S1043452621000498?casa_token=HMLhtaQx-5oAAAAA:46PYNwMkfQTjB_jZ-KKcfvYzHhqf3Fc2-jchhRXlxL1ZJW6uVB09PP8C9vesVXg2OcWgRFI), making caviar a stand-in variable for respondents with seafood-rich diets.

b.  What sort of variation would identify the answer to the research question?

    In order to identify the answer to the research question, we want to figure out the effect that consuming caviar has on one's lifespan. Thus, we could study variation in a few different ways: seeking variation in the frequency with which individuals consume caviar, seeking variation in the amount of caviar-eating individuals consume, seeking variation in individuals' geographic location (i.e. are you closer or further to a caviar-producing region), etc.

c.  Give one suggestion for how the study authors might isolate variation that would identify the answer to the research question.

    In order to isolate variation in order to answer the research question, the authors could isolate for "monthly consumption of caviar" from other potential confounder variables (i.e. geographic location, income level, etc.).

### Exercise 2.3: Alternate Explanations for Correlations 

For each of the following news headlines, assume that the underlying data actually only shows a correlation between the two variables mentioned. Give an alternate explanation for the correlation other than the causal relationship implied by the headline.

a.  “As stock market drops, presidential approval ratings decline.”

    An alternate explanation for this headline could be that the president just announced he was going to instate a mandatory six-day workweek—an announcement that coincidentally went live as the bottom fell out of Yum! brands stock.

b.  “Dates are announced for the downtown summer concert series, driving up sales at downtown restaurants.”

    An alternate explanation here is that many restaurants downtown had just recently reopened after their new construction (due to the downtown area being destroyed by aliens earlier in the year). Thus, sales at the restaurants are due to their reopening, not due to summer concerts going live.

c.  “Unsanitary? Hospital visits linked to 20% increased risk of disease.”

    Oh, wow. An alternate explanation for this headline could be that people who regularly visit hospitals to check on their loved ones then are more likely to develop hypochondria, thus testing for illnesses *more than* those who did not visit someone in the hospital. (In other words: This could be an artificial inflation where equal numbers of people are sick, but only the hospital-visitors are testing.)

d.  “Dress for success! Every CEO follows this office-wear rule.”

    Another explanation for this headline is that those who possess specific kinds of elite cultural capital (i.e. are in possession of elite-valued educational credentials, who know how to converse in these circles, and who can "dress the part" in elite spaces, etc.) are thus able to use their cultural capital to worm their way into the CEO spaces, rather than the other way around.

### Exercise 2.4: "Treatment" v. "Outcome" Variables 

Why is a variable that causes both the "treatment" and "outcome" variables especially concerning for identification? You may want to use the phrase "alternate explanation" in your answer.

A variable that's responsible for causing both the "treatment" and the "outcome" variables is concerning because this may indicate that there is a spurious relationship between the two variables. This spurious relationship (wherein the relationship is not actually X causing Y, but Z causing both X *and* Y), could serve as an "alternate explanation" for the relationship between X and Y. In other words, if controlling for variable Z causes the relationship between X and Y to weaken, we can determine that the relationship between X and Y is at least partly spurious.

### Exercise 2.5: Crikey Shoes! 

Shoe company Crikey claims that people who wear their fancy and expensive professional running-shoe Cool Mistrunner brand run 4 to 5% faster than if they wore an average shoe.

a.  In a few sentences, describe the data-generating process (you will probably leave some things out, that’s okay).

    Huntington-Klein explains that the "GDP" is "all of the different ways" that variables "might be related." Thus, the data-generating process for the "Cool Mistrunner" shoe brand may read as follows: \
    Individuals who have more disposable income can afford more-expensive running shoes than those who have less disposable income. Healthier individuals can typically run faster than unhealthy individuals. Younger individuals can typically run faster than older individuals. Lastly, there may be a difference in male versus female runners that contributes to faster running speeds.

b.  What are possible alternative explanations for this claim, aside from the shoe making the person run faster?

    There may be a placebo effect, wherein athletes who purchase this shoe sincerely believe that it will make them run faster, so the results are skewed; Passionate runners are more likely to buy more expensive shoes and are thus more likely to run faster; People who purchase this shoe brand-new will run more frequently in order to break in the shoe, thus running faster times due to more running in the sneaker; The wealthier people that can afford this shoe can also afford personal training, making them faster athletes.

c.  In running their study, the researchers accounted for some alternative explanations, including: gender, enthusiasm for running, and whether runners have participated in marathons and/or half marathons. Think of an alternative explanation not on this list. What is the implication of not accounting for this alternative explanation?

    An alternate explanation not indicated on this list could be income. As mentioned in earlier answers, class plays a big role in the amount of leisure time, disposable income, and overall health that individuals possess. Consequently, not controlling for class could skew the results, as comparing the running speeds of a fast-food worker (who works 12-hour shifts, has no disposable income to buy fancy running shoes/eat healthier foods/work with a personal trainer, and cannot afford healthcare) versus a CFO (who works 12-hour weeks, has a plethora of disposable income to purchase said fancy running shoes/eat organic food/meet regularly with their personal trainer, and has a personal physician on-call) will tell two very different stories about the effectiveness of the shoe in increasing running speeds.
