<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="L. Harvey">
<meta name="dcterms.date" content="2024-02-26">

<title>Homework-07</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Homework-07_files/libs/clipboard/clipboard.min.js"></script>
<script src="Homework-07_files/libs/quarto-html/quarto.js"></script>
<script src="Homework-07_files/libs/quarto-html/popper.min.js"></script>
<script src="Homework-07_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Homework-07_files/libs/quarto-html/anchor.min.js"></script>
<link href="Homework-07_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Homework-07_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Homework-07_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Homework-07_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Homework-07_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework-07</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>L. Harvey </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 26, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="homework-7" class="level2">
<h2 class="anchored" data-anchor-id="homework-7">Homework #7</h2>
<p>Let’s start by loading in our background homework code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages ---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cobalt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code> cobalt (Version 4.5.3, Build Date: 2024-01-09)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MatchIt'

The following object is masked from 'package:cobalt':

    lalonde</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WeightIt)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper Functions ---</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>love_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  cobalt<span class="sc">::</span><span class="fu">love.plot</span>(x, </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">binary =</span> <span class="st">"std"</span> ,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">stats =</span> <span class="fu">c</span>(<span class="st">"m"</span>, <span class="st">"ks"</span>) ,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">thresholds =</span> <span class="fu">c</span>(.<span class="dv">1</span>, .<span class="dv">05</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">var.order =</span> <span class="st">"adjusted"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">abs =</span> <span class="cn">TRUE</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-7.1-matching-and-weighting" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1-matching-and-weighting">Exercise 7.1: Matching and Weighting</h2>
<p>For these exercises, we’ll be using one of the versions of the “Lalonde data,” which is used in almost every paper on matching. This is data on a job training program (the treatment) that was intended to raise future earnings (the outcome). We load in the data as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"/Users/laurenharvey/Downloads/exercise_data.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Loading this brings in two objects into our global environment: <code>d_exper</code> (the experimental subset of the data) and <code>d</code> (the treated cases and a sample of observational controls from the PSID. The treatment is <code>treat</code> and the outcome is <code>re78</code> (income in $1000s).</p>
<p>Our mission today is to use the experimental subset to set an experimental benchmark, then see how close we can get to this benchmark using various matching and weighting methods.</p>
<p>A breakdown of the variables is as follows:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>age</code></td>
<td>Age in years</td>
</tr>
<tr class="even">
<td><code>educ</code></td>
<td>Years of education</td>
</tr>
<tr class="odd">
<td><code>black</code></td>
<td>1 = Black; 0 otherwise</td>
</tr>
<tr class="even">
<td><code>hisp</code></td>
<td>1 = Hispanic; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>married</code></td>
<td>1 = Married; 0 otherwise</td>
</tr>
<tr class="even">
<td><code>nodegr</code></td>
<td>1 = Married; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>re74</code></td>
<td>1974 income in $1000s</td>
</tr>
<tr class="even">
<td><code>re75</code></td>
<td>1975 income in $1000s</td>
</tr>
<tr class="odd">
<td><code>u74</code></td>
<td>1 = No ’74 income; 0 otherwise</td>
</tr>
<tr class="even">
<td><code>u75</code></td>
<td>1 = No ’75 income; 0 otherwise</td>
</tr>
</tbody>
</table>
<p>Before getting into these exercises, there are a few things that may make life easier:</p>
<p>1. Adding a factor version of the treatment to the data frame for easy plotting</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>d_observed <span class="ot">&lt;-</span> d <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treatment_received =</span> <span class="fu">if_else</span>(treat <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Treatment"</span>, <span class="st">"Control"</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>d_exper <span class="ot">&lt;-</span> d_exper <span class="sc">|&gt;</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treatment_received =</span> <span class="fu">if_else</span>(treat <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Treatment"</span>, <span class="st">"Control"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>2. Creating formula objects that contain the propensity score (or matching) models with and without quadratic terms</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>formula_no_quad <span class="ot">&lt;-</span> <span class="st">"re78 ~ treat + age + educ + black + hisp + married + nodegr + re74 + re75 + u74 + u75"</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>formula_quad <span class="ot">&lt;-</span> <span class="st">"re78 ~ treat + age + I(age^2) + educ + I(educ^2) + black + hisp + married + nodegr + re74 + I(re74^2) + re75 + I(re75^2) + u74 + u75"</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll begin by looking at the experimental data (<code>d_exper</code>). After that, we’ll conduct various forms of matching and weighting on the observational data (<code>d</code>). For each exercise after the first four, the basic workflow will be:</p>
<ol type="1">
<li>Match or weight, as directed</li>
<li>Check balance (overall, if applicable, and by covariate) using graphical and numeric means</li>
<li>Estimate the ATT</li>
</ol>
<p>Let’s get into it.</p>
</section>
<section id="exercise-7.1.1-estimating-the-att" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1.1-estimating-the-att">Exercise 7.1.1: Estimating the ATT</h2>
<p><u>Use the experimental data to estimate the effect of the job training treatment. How much does it appear to affect 1978 income?</u></p>
<p>In order to estimate the effect of the job training treatment in 1978, we compare the <strong>experimental</strong> effects of the treatment versus the effects of the control. This is our naive estimate, which reads as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(d_exper<span class="sc">$</span>re78[d_exper<span class="sc">$</span>treat <span class="sc">==</span> <span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">mean</span>(d_exper<span class="sc">$</span>re78[d_exper<span class="sc">$</span>treat <span class="sc">==</span> <span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8863038</code></pre>
</div>
</div>
<p>The naive estimate for the experimental data is $886.30.</p>
<p><u>Now look at the observational data (for all exercises from now on). How large is the raw difference in 1978 income between the treatment group and the PSID comparison group?</u></p>
<p>We again find the naive estimate by subtracting the effects of the treatment (but this time, from the <strong>observed</strong> data set):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(d_observed<span class="sc">$</span>re78[d_observed<span class="sc">$</span>treat <span class="sc">==</span> <span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">mean</span>(d_observed<span class="sc">$</span>re78[d_observed<span class="sc">$</span>treat <span class="sc">==</span> <span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -16.54134</code></pre>
</div>
</div>
<p>The naive estimate for the observational data is -$16,541.34. Clearly, there are some shenanigans ensuing and likely some variables that we are not properly addressing.</p>
</section>
<section id="exercise-7.1.2-estimating-with-regression" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1.2-estimating-with-regression">Exercise 7.1.2: Estimating with Regression</h2>
<p><u>Try to estimate the effect of the treatment using regression. What does regression say the effect of the program is?</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mod_no_adjustments <span class="ot">&lt;-</span> <span class="fu">lm</span>(re78 <span class="sc">~</span> treat, <span class="at">data =</span> d_exper)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(mod_no_adjustments)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       treat 
  5.0900482   0.8863038 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod_no_adjustments)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    5.09      0.303     16.8  9.54e-54
2 treat          0.886     0.472      1.88 6.09e- 2</code></pre>
</div>
</div>
<p>Without making any adjustments, there is an estimated effect of treatment as increasing income by $886.30.</p>
<p>What happens to our model when we <em>do</em> include adjustments? (Note: This is using the model with quadratic variables)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mod_with_adjustments <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula_quad, <span class="at">data =</span> d_exper)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_with_adjustments)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = formula_quad, data = d_exper)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.465  -4.435  -1.491   3.296  53.923 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 10.985771   5.330026   2.061   0.0397 *
treat        0.813809   0.468155   1.738   0.0826 .
age         -0.134437   0.216422  -0.621   0.5347  
I(age^2)     0.002486   0.003606   0.689   0.4909  
educ        -1.181805   1.014489  -1.165   0.2444  
I(educ^2)    0.079069   0.055673   1.420   0.1560  
black       -1.418940   0.800419  -1.773   0.0767 .
hisp         0.265324   1.049633   0.253   0.8005  
married      0.152768   0.654873   0.233   0.8156  
nodegr       0.312865   0.910017   0.344   0.7311  
re74        -0.182819   0.180101  -1.015   0.3104  
I(re74^2)    0.010120   0.005322   1.902   0.0576 .
re75         0.181010   0.193615   0.935   0.3502  
I(re75^2)   -0.003420   0.006532  -0.524   0.6007  
u74          0.712339   1.036152   0.687   0.4920  
u75         -0.947228   0.968743  -0.978   0.3285  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.132 on 706 degrees of freedom
Multiple R-squared:  0.05846,   Adjusted R-squared:  0.03846 
F-statistic: 2.922 on 15 and 706 DF,  p-value: 0.0001621</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod_with_adjustments)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 5
   term        estimate std.error statistic p.value
   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept) 11.0       5.33        2.06   0.0397
 2 treat        0.814     0.468       1.74   0.0826
 3 age         -0.134     0.216      -0.621  0.535 
 4 I(age^2)     0.00249   0.00361     0.689  0.491 
 5 educ        -1.18      1.01       -1.16   0.244 
 6 I(educ^2)    0.0791    0.0557      1.42   0.156 
 7 black       -1.42      0.800      -1.77   0.0767
 8 hisp         0.265     1.05        0.253  0.801 
 9 married      0.153     0.655       0.233  0.816 
10 nodegr       0.313     0.910       0.344  0.731 
11 re74        -0.183     0.180      -1.02   0.310 
12 I(re74^2)    0.0101    0.00532     1.90   0.0576
13 re75         0.181     0.194       0.935  0.350 
14 I(re75^2)   -0.00342   0.00653    -0.524  0.601 
15 u74          0.712     1.04        0.687  0.492 
16 u75         -0.947     0.969      -0.978  0.329 </code></pre>
</div>
</div>
<p>When we run a model that <em>does</em> include adjustments and quadratic terms, the estimated effect of treatment is still negative.</p>
</section>
<section id="exercise-7.1.3-exact-matching" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1.3-exact-matching">Exercise 7.1.3: Exact Matching</h2>
<p><u>Begin by exact matching on all the dummy variables.</u></p>
<p>The code to create matchy-matchiness on dummy variables is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>exact_matchy_out <span class="ot">&lt;-</span> <span class="fu">matchit</span>(treat <span class="sc">~</span> black <span class="sc">+</span> hisp <span class="sc">+</span> married <span class="sc">+</span> nodegr <span class="sc">+</span> u74 <span class="sc">+</span> u75, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> d_observed, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"exact"</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">estimand =</span> <span class="st">"ATT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><u>How many treated cases cannot be matched?</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exact_matchy_out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
matchit(formula = treat ~ black + hisp + married + nodegr + u74 + 
    u75, data = d_observed, method = "exact", estimand = "ATT")

Summary of Balance for All Data:
        Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
black          0.8013        0.2517          1.3776          .    0.5497
hisp           0.0943        0.0325          0.2113          .    0.0617
married        0.1684        0.8730         -1.8833          .    0.7047
nodegr         0.7306        0.3434          0.8728          .    0.3872
u74            0.4411        0.0723          0.7427          .    0.3688
u75            0.3737        0.0890          0.5885          .    0.2847
        eCDF Max
black     0.5497
hisp      0.0617
married   0.7047
nodegr    0.3872
u74       0.3688
u75       0.2847

Summary of Balance for Matched Data:
        Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
black          0.8049        0.8049              -0          .         0
hisp           0.0941        0.0941              -0          .         0
married        0.1568        0.1568              -0          .         0
nodegr         0.7282        0.7282              -0          .         0
u74            0.4216        0.4216              -0          .         0
u75            0.3868        0.3868              -0          .         0
        eCDF Max Std. Pair Dist.
black          0               0
hisp           0               0
married        0               0
nodegr         0               0
u74            0               0
u75            0               0

Sample Sizes:
              Control Treated
All           2213.       297
Matched (ESS)   59.52     287
Matched       2092.       287
Unmatched      121.        10
Discarded        0.         0</code></pre>
</div>
</div>
<p>Our output tells us that 121 cases from the “control” group in data set <code>d_observed</code> that could not be matched. Furthermore, there were 10 cases from the “treated” group in data set <code>d_observed</code> that could not be matched.</p>
<p><u>What is the (FS)ATT estimate?</u></p>
<p>Remember that dropped cases have a weight of 0 (because we aren’t using them!).</p>
<ol type="1">
<li>In order to find the FSATT, we have to account for these dropped cases.</li>
<li>We want to estimate the FSATT by using a regression model.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>exact_match_data <span class="ot">&lt;-</span> <span class="fu">match.data</span>(exact_matchy_out)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>finding_fsatt_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> re78 <span class="sc">~</span> treat, </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> exact_match_data, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">weights =</span> weights)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(finding_fsatt_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = re78 ~ treat, data = exact_match_data, weights = weights)

Weighted Residuals:
     Min       1Q   Median       3Q      Max 
-109.035    0.610    2.407    4.770  113.179 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   8.2437     0.2317  35.577  &lt; 2e-16 ***
treat        -2.3863     0.6671  -3.577 0.000354 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.6 on 2377 degrees of freedom
Multiple R-squared:  0.005354,  Adjusted R-squared:  0.004936 
F-statistic:  12.8 on 1 and 2377 DF,  p-value: 0.0003545</code></pre>
</div>
</div>
<p>The FSATT is -2.3863, meaning that the estimated ATT is a decrease in income of $2,386.30 (as compared to those who did <em>not</em> receive the treatment).</p>
</section>
<section id="exercise-7.1.4-estimating-propensity" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1.4-estimating-propensity">Exercise 7.1.4: Estimating Propensity</h2>
<p><u>Use the observational data to estimate each case’s propensity to receive treatment using <code>glm()</code>. Use a logistic regression with quadratic terms for age, education, 1974 income, and 1975 income. Spend a few moments thinking about what this model says.</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>propensity_mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> treat <span class="sc">~</span> age <span class="sc">+</span> <span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> educ <span class="sc">+</span> <span class="fu">I</span>(educ<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> black <span class="sc">+</span> hisp <span class="sc">+</span> married <span class="sc">+</span> nodegr <span class="sc">+</span> re74 <span class="sc">+</span> <span class="fu">I</span>(re74<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> re75 <span class="sc">+</span> <span class="fu">I</span>(re75<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> u74 <span class="sc">+</span> u75, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> d_observed, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(propensity_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = treat ~ age + I(age^2) + educ + I(educ^2) + black + 
    hisp + married + nodegr + re74 + I(re74^2) + re75 + I(re75^2) + 
    u74 + u75, family = "binomial", data = d_observed)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -4.0860109  2.0931327  -1.952 0.050926 .  
age          0.0885744  0.0972988   0.910 0.362647    
I(age^2)    -0.0029497  0.0014994  -1.967 0.049147 *  
educ         0.8446841  0.3120974   2.706 0.006800 ** 
I(educ^2)   -0.0468130  0.0162233  -2.886 0.003908 ** 
black        1.9621150  0.2719006   7.216 5.34e-13 ***
hisp         2.4117400  0.4512282   5.345 9.05e-08 ***
married     -2.0307420  0.2332962  -8.705  &lt; 2e-16 ***
nodegr       0.0177758  0.3420739   0.052 0.958557    
re74        -0.0560163  0.0511241  -1.096 0.273214    
I(re74^2)    0.0012223  0.0016798   0.728 0.466828    
re75        -0.1544280  0.0418499  -3.690 0.000224 ***
I(re75^2)    0.0004442  0.0012405   0.358 0.720281    
u74          2.3537938  0.4966435   4.739 2.14e-06 ***
u75         -1.2273787  0.4540319  -2.703 0.006866 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1825.16  on 2509  degrees of freedom
Residual deviance:  610.11  on 2495  degrees of freedom
AIC: 640.11

Number of Fisher Scoring iterations: 9</code></pre>
</div>
</div>
<p>The <code>propensity_mod</code> model produces estimates of receiving treatment on the basis of the variables included in the model (i.e., <code>age</code>, <code>educ</code>, <code>black</code>, <code>hisp</code>, <code>married</code>, <code>nodegr</code>, <code>re74</code>, <code>re75</code>, <code>u74</code>, and <code>u75</code>). Our intercept is still negative, as are two of the four continuous variables included in this formula (i.e., <code>I(age^2)</code> and <code>I(educ^2)</code>).</p>
<p><u>Look at the density plots of the p-score for treated and untreated groups.</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutate the data frame</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>for_the_plot <span class="ot">&lt;-</span> d_observed <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_score =</span> <span class="fu">predict</span>(propensity_mod, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> d_observed, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Then create the plot</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>for_the_plot <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p_score)) <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> treat) <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Homework-07_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above code produces two density plots, sorted into either 0 (did not receive the treatment) or 1 (received the treatment). Both plots show non-linear functions (which is a consequence of the quadratic variables included in the formula, like <code>I(age^2)</code> and <code>I(re74^2)</code>). Lastly, the treated group had a peak propensity score of about 0.80, while the control group had a plateaued propensity score throughout the density plot.</p>
</section>
<section id="exercise-7.1.5-using-weightit" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1.5-using-weightit">Exercise 7.1.5: Using <code>WeightIt</code></h2>
<p><u>Estimate propensity scores and ATT weights using <code>WeightIt()</code>. Ignore the warnings you get.</u></p>
<p>Let’s first examine propensity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>propensity_matching <span class="ot">&lt;-</span> <span class="fu">weightit</span>(treat <span class="sc">~</span> age <span class="sc">+</span> <span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> educ <span class="sc">+</span> <span class="fu">I</span>(educ<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> black <span class="sc">+</span> hisp <span class="sc">+</span> married <span class="sc">+</span> nodegr <span class="sc">+</span> re74 <span class="sc">+</span> <span class="fu">I</span>(re74<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> re75 <span class="sc">+</span> <span class="fu">I</span>(re75<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> u74 <span class="sc">+</span> u75, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">"ps"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimand =</span> <span class="st">"ATT"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> d_observed) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some extreme weights were generated. Examine them with `summary()` and
maybe trim them with `trim()`.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the summary </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(propensity_matching)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Summary of weights

- Weight ranges:

        Min                                   Max
treated   1 ||                             1.0000
control   0 |---------------------------| 83.9742

- Units with the 5 most extreme weights by group:
                                                
            2218    2217    2216    2215    2214
 treated       1       1       1       1       1
            1485    1484    1478      56    1521
 control 22.7435 22.7435 27.3148 48.3254 83.9742

- Weight statistics:

        Coef of Var   MAD Entropy # Zeros
treated       0.000 0.000  -0.000       0
control      12.211 1.732   3.841       0

- Effective Sample Sizes:

           Control Treated
Unweighted 2213.       297
Weighted     14.75     297</code></pre>
</div>
</div>
<p>The summary of <code>propensity_matching</code> reveals that the weights used in this sample range from 1-1 for our treated values (because we <strong>do not</strong> adjust for treated values). The weights used to adjust the control values, however, range from 0-83.97 (meaning that we have at least one control case that is seemingly-identical to a treatment case, but is not, and at least one control case that is aggressively antithetical to the treatment case and requires serious weighting).</p>
<p><u>Estimate the ATT.</u></p>
<p>In order to estimate the ATT, we can create a linear model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>att_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(re78 <span class="sc">~</span> treat, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> d_observed, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">weights =</span> propensity_matching<span class="sc">$</span>weights)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(att_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = re78 ~ treat, data = d_observed, weights = propensity_matching$weights)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-24.136   0.086   0.418   1.226  54.332 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   4.8371     0.1714  28.229  &lt; 2e-16 ***
treat         1.1393     0.2682   4.248 2.23e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.555 on 2508 degrees of freedom
Multiple R-squared:  0.007144,  Adjusted R-squared:  0.006748 
F-statistic: 18.05 on 1 and 2508 DF,  p-value: 2.234e-05</code></pre>
</div>
</div>
<p>The ATT produced in this model is <code>1.139</code>, meaning that the average effect of receiving treatment (i.e., training) increased income by $1,140.00. Importantly, our ATT is now <strong>positive</strong>, whereas the previous models estimated a <strong>negative</strong> treatment effect.</p>
<p><u>Check for covariate balance.</u></p>
<p>To check the covariate balance, let’s add in a love plot in order to better see what’s going on with this data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">love_plot</span>(propensity_matching)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Homework-07_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The love plot reveals a few things. First, almost all of the adjusted variables fall within a tenth of a percentile outside of the standard deviation on the Absolute Standardized Means Differences (ASMD) visualization. Second, despite the adjusted variables mapping almost-perfectly onto the acceptable range of adjustment—I’m looking at you, <code>u74</code>—for the ASMD graphic, there is a lot of messiness on the Kolmogorov-Smirnov Distance (KSD) visualization. Specifically, the distance between nearly every adjusted variable on the KSS graphic is outside of the range of acceptability.</p>
<p>Thus, these graphics indicate to us that there are some adjustments that need to be made to our adjustments.</p>
</section>
<section id="exercise-7.1.6-entropy-balancing" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7.1.6-entropy-balancing">Exercise 7.1.6: Entropy Balancing</h2>
<p><u>Estimate propensity scores and ATT weights using “entropy balancing.”</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>entropy_balance_mod <span class="ot">&lt;-</span> <span class="fu">weightit</span>(treat <span class="sc">~</span> age <span class="sc">+</span> <span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> educ <span class="sc">+</span> <span class="fu">I</span>(educ<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> black <span class="sc">+</span> hisp <span class="sc">+</span> married <span class="sc">+</span> nodegr <span class="sc">+</span> re74 <span class="sc">+</span> <span class="fu">I</span>(re74<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> re75 <span class="sc">+</span> <span class="fu">I</span>(re75<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> u74 <span class="sc">+</span> u75, </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> d_observed,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">"ebal"</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">moments =</span> <span class="dv">3</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimand =</span> <span class="st">"ATT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The optimization failed to converge in the alotted number of
iterations. Try increasing `maxit`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some extreme weights were generated. Examine them with `summary()` and
maybe trim them with `trim()`.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(entropy_balance_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Summary of weights

- Weight ranges:

        Min                                    Max
treated   1 ||                              1.0000
control   0 |---------------------------| 230.6791

- Units with the 5 most extreme weights by group:
                                                   
            2218     2217     2216    2215     2214
 treated       1        1        1       1        1
               4     1587     1613    1540     1521
 control 96.5427 101.3705 110.4505 138.535 230.6791

- Weight statistics:

        Coef of Var   MAD Entropy # Zeros
treated       0.000 0.000   0.000       0
control       8.451 1.768   3.495      35

- Effective Sample Sizes:

           Control Treated
Unweighted 2213.       297
Weighted     30.57     297</code></pre>
</div>
</div>
<p>Similar to what we did in the previous exercise, the summary of <code>entropy_balance_mod</code> reveals that there is a consistently-applied weight of 1 to our treatment group and a range of 0-230.68 for our control group. The findings are similar to the results of the previous <code>WeightIt</code> output, as it indicates that there is at least one control group case that appears identical to a treatment group case and that there is at least one control case that needs serious adjusting.</p>
<p><u>Confirm that you’ve achieved balance on the means and the variances of the covariates.</u></p>
<p>Let’s check the covariate balancing with a final love plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">love_plot</span>(entropy_balance_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Homework-07_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Better! The adjusted values in the ASMD are now all beautifully within the range of acceptable error, and while the KSD is still ugly, it’s less of a mess than before.</p>
<p><u>Estimate the ATT.</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>last_att_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(re78 <span class="sc">~</span> treat, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> d_observed, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">weights =</span> entropy_balance_mod<span class="sc">$</span>weights)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(last_att_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = re78 ~ treat, data = d_observed, weights = entropy_balance_mod$weights)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-68.289   0.047   0.575   2.386 142.862 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   5.8019     0.1696  34.214   &lt;2e-16 ***
treat         0.1744     0.4930   0.354    0.724    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.977 on 2508 degrees of freedom
Multiple R-squared:  4.991e-05, Adjusted R-squared:  -0.0003488 
F-statistic: 0.1252 on 1 and 2508 DF,  p-value: 0.7235</code></pre>
</div>
</div>
<p>Lastly, the ATT produced in this model is <code>0.1744</code>, meaning that the average effect of receiving treatment is an increase in income by $174.40. Again, our ATT is positive.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>